### ISSUE TITLE
Place block relative to right and bottom in this case

### ISSUE THREAD

**Issue by rudnitskih** [scandy5/minus-nerves#13]
![image](https://user-images.githubusercontent.com/8848858/47633925-4ec5f000-db58-11e8-9940-e492e4801a47.png)

![image](https://user-images.githubusercontent.com/8848858/47633926-52f20d80-db58-11e8-8b10-b54f4ddc76d0.png)

**Comment by scandy5** [comment]
done

**Comment by rudnitskih** [comment]
![image](https://user-images.githubusercontent.com/8848858/47912522-9ecaec80-dea1-11e8-9b88-e9e7449e2fac.png)

**Comment by rudnitskih** [comment]
Possible solution like this

![image](https://user-images.githubusercontent.com/8848858/47912566-cc179a80-dea1-11e8-8109-42bcf0838d0e.png)
