### ISSUE TITLE
Looks like 6 spans is not enough for right block, use 7

### ISSUE THREAD

**Issue by rudnitskih** [scandy5/minus-nerves#14]
![image](https://user-images.githubusercontent.com/8848858/47634088-ed525100-db58-11e8-817b-7699cc427166.png)

**Comment by scandy5** [comment]
done

**Comment by rudnitskih** [comment]
Other blocks also should take 7 spans:
![image](https://user-images.githubusercontent.com/8848858/47912594-e6517880-dea1-11e8-8cfa-9ac94c2d6bfa.png)












![image](https://user-images.githubusercontent.com/8848858/47913528-1fd7b300-dea5-11e8-9c8f-c52604233010.png)
