### ISSUE TITLE
Нужно заменить картинку

### ISSUE THREAD

**Issue by ArtemChubatyi** [scandy5/minus-nerves#2]
![default](https://user-images.githubusercontent.com/43701381/47622328-8dce5400-db0c-11e8-8a6d-22c28ac48ea2.png)

Я так понимаю - ты вытащил блок картинкой, нужно тогда, хотя бы, её подправить, что бы небыло белых линий по краям.

**Comment by rudnitskih** [comment]
@scandy5 why you decided to use images like this?

**Comment by rudnitskih** [comment]
Still valid comment:
![image](https://user-images.githubusercontent.com/8848858/47956275-91e5f000-dfaa-11e8-9592-1767e7ca9fe0.png)

**Comment by rudnitskih** [comment]
Why do you still use images for these blocks? You can create square with text using CSS.
