### ISSUE TITLE
Remove line, pull text into right, align to center with menu items

### ISSUE THREAD

**Issue by rudnitskih** [scandy5/minus-nerves#24]
![image](https://user-images.githubusercontent.com/8848858/47913815-1c90f700-dea6-11e8-9e88-c1cb7727050d.png)

**Comment by rudnitskih** [comment]
Try to make it a little bit cooler:
![image](https://user-images.githubusercontent.com/8848858/47956303-0fa9fb80-dfab-11e8-9f96-bc2f2481e8ed.png)

**Comment by scandy5** [comment]
Не понял, это как?

**Comment by rudnitskih** [comment]
ну просто заверстай это блок немного подругому на телефоне, сейчас он съедает много места:
![image](https://user-images.githubusercontent.com/8848858/47963024-5b51b900-e02e-11e8-9f20-9ff0e81f5c43.png)

**Comment by rudnitskih** [comment]
Теперь еще хуже:
![image](https://user-images.githubusercontent.com/8848858/47964256-bd66ea00-e03f-11e8-9df5-5d9eaa94ee1e.png)

Заверстай так как я скинул скриншоте выше.
