### ISSUE TITLE
You load a lot of JS for this small project. Make you sure all loaded is required.

### ISSUE THREAD

**Issue by rudnitskih** [scandy5/minus-nerves#29]
![image](https://user-images.githubusercontent.com/8848858/47914400-274c8b80-dea8-11e8-8349-6bd712f72d32.png)

**Comment by scandy5** [comment]
включить uglify или я не понял?

**Comment by rudnitskih** [comment]
Крупные библиотеки типа angular и react весят 100кб, а у тебя тут целых 400кб JS кода. Это где то 100 000 строк кода. У тебя на странице только font-awesome и gamburger используют JS. Как то многовато финальный JS весит.

**Comment by scandy5** [comment]
в файле вродебы нет ничего лишнего, я просмотрел мельком до того, как минифицировал

**Comment by rudnitskih** [comment]
Ты грузишь all версию, посмотри документацию что такое all, solid, regular, brands. Возможно они тебе и не нужны: https://fontawesome.com/how-to-use/on-the-web/setup/getting-started?using=svg-with-js 

Возможно ты можешь тянуть `min` сборки, а не обычные.

![image](https://user-images.githubusercontent.com/8848858/47963060-ea5ed100-e02e-11e8-99b0-d84ccd6efb7d.png)

Зачем тебе jquery?
![image](https://user-images.githubusercontent.com/8848858/47963065-1ed28d00-e02f-11e8-88d2-31e1bb2dce08.png)

**Comment by scandy5** [comment]
я его у себя удалил, а на гите не удалил *facepalm*
