### ISSUE TITLE
Optional: try to optimize images with some CLI tool 

### ISSUE THREAD

**Issue by rudnitskih** [scandy5/minus-nerves#5]
![image](https://user-images.githubusercontent.com/8848858/47632680-c9d8d780-db53-11e8-98a4-f73b0654f9b4.png)

https://www.npmjs.com/package/gulp-imagemin

**Comment by rudnitskih** [comment]
Did you optimize something? 

![image](https://user-images.githubusercontent.com/8848858/47912275-bb1a5980-dea0-11e8-9073-2945686832da.png)

**Comment by scandy5** [comment]
Я юзал программу Caesium для некоторых картинок, которые было возможно сжать без потери качества, или я что-то не то сделал?)

**Comment by rudnitskih** [comment]
я просто вижу что никакой оптимизации не произошло - как `img.png` весил 900кб так и продолжает весить.

**Comment by rudnitskih** [comment]
возможно они уже и так по максимуму оптимизированы

**Comment by scandy5** [comment]
я опять попытался, ничего не меняется
